
// Generated by Cadence Genus(TM) Synthesis Solution 16.12-s027_1
// Generated on: Jan 11 2019 00:42:10 GMT (Jan 11 2019 00:42:10 UTC)

// Verification Directory fv/control 

module control(Clock, nReset, Req, nZ, nBorrow, Done, Load, LoadAcc,
     LoadResult, ShiftIn);
  input Clock, nReset, Req, nZ, nBorrow;
  output Done, Load, LoadAcc, LoadResult, ShiftIn;
  wire Clock, nReset, Req, nZ, nBorrow;
  wire Done, Load, LoadAcc, LoadResult, ShiftIn;
  wire [2:0] cnt;
  wire [1:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_38, n_39, n_40, n_41, n_42;
  wire n_44, n_46, n_47, n_48;
  scandtype \cnt_reg[1] (.nReset (nReset), .Clock (Clock), .D (n_47),
       .Q (cnt[1]), .nQ (n_0));
  scandtype \cnt_reg[2] (.nReset (nReset), .Clock (Clock), .D (n_48),
       .Q (cnt[2]), .nQ (n_5));
  scandtype \cnt_reg[0] (.nReset (nReset), .Clock (Clock), .D (n_46),
       .Q (cnt[0]), .nQ (n_32));
  nand3 g965(.A (n_17), .B (n_39), .C (n_30), .Y (n_48));
  mux2 g961(.S (cnt[1]), .I0 (n_42), .I1 (n_38), .Y (n_47));
  nand3 g964(.A (n_33), .B (n_27), .C (n_31), .Y (n_46));
  scandtype \state_reg[0] (.nReset (nReset), .Clock (Clock), .D (n_41),
       .Q (state[0]), .nQ (n_9));
  scandtype \state_reg[1] (.nReset (nReset), .Clock (Clock), .D (n_44),
       .Q (state[1]), .nQ (n_4));
  inv g978(.A (n_40), .Y (LoadResult));
  inv g971(.A (n_35), .Y (n_44));
  inv g972(.A (n_36), .Y (ShiftIn));
  nand2 g979(.A (n_20), .B (n_15), .Y (n_42));
  nand2 g968(.A (n_22), .B (n_24), .Y (n_41));
  nand3 g983(.A (n_32), .B (n_18), .C (n_0), .Y (n_40));
  nand2 g966(.A (n_23), .B (cnt[2]), .Y (n_39));
  nand3 g969(.A (n_3), .B (n_16), .C (n_6), .Y (n_38));
  inv g973(.A (n_26), .Y (Done));
  nand2 g975(.A (n_14), .B (n_34), .Y (n_36));
  nand2 g974(.A (n_25), .B (n_34), .Y (n_35));
  nand2 g980(.A (n_34), .B (n_32), .Y (n_33));
  nand3 g988(.A (cnt[1]), .B (n_29), .C (cnt[2]), .Y (n_31));
  nand3 g985(.A (cnt[0]), .B (n_29), .C (cnt[1]), .Y (n_30));
  nand2 g982(.A (n_13), .B (n_34), .Y (LoadAcc));
  nand3 g970(.A (cnt[0]), .B (n_10), .C (state[1]), .Y (n_27));
  nand2 g976(.A (n_25), .B (n_21), .Y (n_26));
  nand2 g977(.A (n_7), .B (n_29), .Y (n_24));
  nand2 g981(.A (n_8), .B (n_9), .Y (n_23));
  nand2 g986(.A (Req), .B (n_21), .Y (n_22));
  nand2 g993(.A (n_29), .B (cnt[0]), .Y (n_20));
  inv g991(.A (n_34), .Y (Load));
  inv g984(.A (n_17), .Y (n_18));
  nand2 g992(.A (n_12), .B (n_32), .Y (n_16));
  nand2 g996(.A (n_15), .B (n_11), .Y (n_34));
  inv g997(.A (n_13), .Y (n_14));
  inv g998(.A (n_12), .Y (n_21));
  inv g1002(.A (n_11), .Y (n_29));
  nand3 g987(.A (cnt[1]), .B (n_9), .C (cnt[2]), .Y (n_10));
  nand2 g994(.A (n_2), .B (state[1]), .Y (n_8));
  inv g990(.A (n_7), .Y (n_25));
  nand3 g989(.A (n_9), .B (state[1]), .C (n_5), .Y (n_17));
  nand2 g999(.A (state[1]), .B (n_5), .Y (n_6));
  nand2 g1000(.A (n_1), .B (nBorrow), .Y (n_13));
  nand2 g1001(.A (n_9), .B (n_4), .Y (n_12));
  nand2 g1005(.A (state[1]), .B (n_9), .Y (n_15));
  nand2 g1006(.A (state[0]), .B (n_4), .Y (n_11));
  nand3 g995(.A (cnt[1]), .B (cnt[0]), .C (cnt[2]), .Y (n_7));
  nand2 g1003(.A (state[0]), .B (cnt[2]), .Y (n_3));
  nand2 g1004(.A (cnt[0]), .B (cnt[1]), .Y (n_2));
  inv g1007(.A (nZ), .Y (n_1));
endmodule

